### ISSUE TITLE
Various Fixes

### ISSUE THREAD

**Issue by Rspigler** [JWWeatherman/yeticold#115]
- Burn several copies to disk instead of a single copy - this is a simple fix in the instructions (the application used allows for this) and this increases redundancy in case of damage to the CD's

- Label the Level of the Seed on each CD in addition to the Seed number, instead of just the Seed # (Users are likely to have a wallet setup for more than one Level, this way they won't mix up seeds, which could be dangerous).

@JWWeatherman @willweatherman

**Comment by fresheneesz** [comment]
I recommend labeling with a little more information.  Eg label the CD with a date, level, and a name that means something to the user, and then "Seed 1", for example "Primary Wallet 2021-01-25 Level 3 Seed 1".

**Comment by JWWeatherman** [comment]
- We want them to have a couple extra clicks to burn the CDs rather than just use the built in duplication so the instructions are a bit more clear and it harder to mess up and not know how to continue.
- I don't want to add anything more to the packets for privacy reasons (in general). We do already distingiush between a L2/3 and an L1 in the seed template. We don't want to be more specific as hiers can recover it as either an L2 or L3.
- Whatever we add should be added to the seedtemplate.txt rather than having the user hand write stuff. If they mix a bunch of envelope contents thats pretty goofy and they will still figure it out with some brute force work.
