### ISSUE TITLE
Big list of suggestions for improvement

### ISSUE THREAD

**Issue by onyb** [JWWeatherman/yeticold#69]
## Preface

I did some reading on the codebase and the documentation, notably to find potential attack vectors. Following is a brain dump of what I think are low-hanging fruits that would harden the security of a setup such as Yeti Cold. The idea is to provide pointers to the authors and members of the community to improve the software.

The RPC commands issued to Bitcoin Core look fine to me, and use of descriptors for private keys is quite future-proof. However, I think there are practical attacks that can be pulled off at the web application level, without ever compromising the full node. Since YetiCold is meant to be used for high-value cold storage, the sophistication of possible attacks should not be underestimated.

### Use SSL certificates

For the kind of multi-node setup that YetiCold describes, it is important to ensure that JSON-RPC communication happens over SSL. Fortunately, it is quite easy to set this up as `bitcoind` already knows how to accept JSON-RPC over HTTPS.

#### Recommendation

Generate a self-signed certificate, and enable `rpcssl`.

### Use `rpcauth` instead of username and password

It's more secure to use `rpcauth` over RPC username and password, since the credentials are salted. For local authentication, you can use RPC cookie authentication, if you have a use-case for it.

#### Recommendation

You can use [this](https://github.com/bitcoin/bitcoin/blob/master/share/rpcauth/rpcauth.py) utility to generate credentials, that can be passed to `bitcoin-cli` using the `-rpcauth` flag.

### Using `subprocess` is a security hazard

Let's look at an example based on a common pattern in `appyeticold.py`:

```py
import subprocess

rpcusername = "<my yeti username>"  # Not safe!
subprocess.call(f'echo "{rpcusername}"', shell=True)
```

The above code is vulnerable to shell injection. An attacker can easily print the secrets to stdout, or even mutate them in a way that the attacker will reveal only in exchange of a ransom. Here's an example:

```py
rpcusername = "$(cat ~/.ssh/id_rsa)"
```

#### Recommendation

At the minimum, remove `shell=True`. The ideal fix would be to use the `bitcoinrpc` library for the RPC transport which you already started using in a few places.

### Committing binary files to the repo is dangerous

There is no way to verify that the virtual environment uploaded in the `flask` directory or the files in `__pycache__` do not have a malware inserted by a contributor or the authors.

#### Recommendation

The suggestions in #49 are good enough.

### Use of `global` is not thread-safe

Use of `global` is generally discouraged in Python. From what I can understand, `global` has been used to share information between different Flask routes. This is fine as long as the Flask app runs as a development server on a single thread, but as soon as you use a WSGI server (which you should definitely consider using) such as gunicorn or uwsgi, you'll start seeing weird side-effects.

#### Recommendation

For storing information during a Flask application context, you can use `flask.g` which uses thread-local storage. For persisting information across multiple API calls, using an embedded database would be the cleanest solution. However, if you don't want to introduce the complexity of a database, you can do something like this.

```py
from flask import Flask, jsonify


def writer_handler_func(state):
    def g():
        state["key"] += 1  # modify the state

        return jsonify(state)

    return g


def reader_handler_func(state):
    def g():
        return jsonify(state)  # read the state

    return g


def main():
    # Initialize the Flask app
    app = Flask(__name__)

    # Initialize a mutable state. Optionally partition the state to prevent
    # passing the entire thing to every handler.
    state = {"key": 0}

    app.add_url_rule("/read", "read", reader_handler_func(state))
    app.add_url_rule("/write", "write", writer_handler_func(state))

    app.run()


main()
```

### Partial executable paths are unsafe

Another common pattern I found in `appyeticold.py` is the use of `~` prefixed paths in `subprocess` calls. Even if it might seem safe at first glance, it can be exploited by someone who is motivated enough. Let's take a look at the following example from the codebase (shortened for brevity):

```py
selectedutxo = subprocess.Popen(['python3 ~/yeticold/utils/scanqrcode.py'], shell=True, ...)
selectedutxo = eval(selectedutxo.decode("utf-8"))
```

An attacker just needs to set the `HOME` environment variable to customize the expansion of `~`, and thereby trigger the execution of a malicious script. Here's a hypothetical example:

```sh
HOME=/path/controlled/by/attacker python -c \
    "import subprocess; subprocess.call('~/yeticold/whatever.py', shell=True))"  # corrupt some private key
```

#### Recommendation

Use absolute paths. Better if you're running the app inside Docker, allowing you to jail the runtime inside an isolated environment.

### Using `eval` is dangerous

You should almost never use `eval` in Python that accepts an unsanitized string. An attacker could pass an innocuous-looking camera feed that translates to a malicious Python expression.

#### Recommendation

Stop using `eval` for executing Python code from different modules/files, and use native calls/imports instead.

### Use I/O streams instead of R/W to files on disk

Writing to and reading from files (such as image data) is not performant enough, and is very cumbersome to manage paths, cleanup temporary files, etc.

#### Recommendation

Use in-memory I/O streams: https://docs.python.org/3/library/io.html

### Represent amounts in sats

Avoid usage of `float` with amounts.

#### Recommendation

In general, it is a good practice to convert numbers to base units (i.e. Satoshis), before performing mathematical operations with them. Try to avoid casts to `float`, which can have weird precision behaviour in Python.

### Code-style

This point may seem quite obvious, but it wasn't very easy for me to understand the code. Having a readable codebase is paramount for something like YetiCold where users need to understand what's going on to feel confident using it.

#### Recommendation

See #49.

**Comment by willweatherman** [comment]
Fixed

**Comment by willweatherman** [comment]
Hi,

1. SSL certificate: We are running over localhost so it doesn't need any sort of certificates.
2. RPCauth: I am not sure where we were using a username and a password but I completely removed the third party lib for RPC commands and so we only use bitcoin-cli. I do generate a password as a random number but there is no reason for this to be completely secure.
3. Subprocess: We are having the user run this code on a freshly installed ubuntu laptop to minimize possible viruses and attacker code. If they got a hold of the laptop and could change env vars then there's not much you can do and a motivated hacker could get in somehow. One of the ways to completely erase this issue would be to use an offline laptop as we do.
4. Eval: We saw this and have removed it, Thank you.
5. Binary files in git: Yes this was not intentional and has been fixed.
6. Global is not thread-safe: Yes this is probably true but we have no intention of moving from our current setup (the dev server) and if we do we will have to change quite a bit of code anyway.
7. Parsial paths: Again if an attacker gets that far he would either not be able to transfer data off the offline machine or if he found a way to do so it would not matter how he attacks. I would also not be able to change from the ~ because I often do not know what the actual path is. The only other place that I get the home is directly from the HOME env var anyway.
8. I/O streams: So far this has not been a problem at all but if we do a lot more read/wright then we will change this and thank you for this suggestion.
9. We have compactly removed the account handling as of bitcoin core 0.21.0 introducing descriptor wallets.
10. This has been mostly mitigated by the most recent update including the use of the descriptor wallets and is continually improved as far as being readable.


Thank you for this feedback-
Will.
